# Generated by Django 3.2.6 on 2021-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='info',
            field=models.JSONField(),
        ),
    ]
